apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms3-deployment
  labels:
    component: ms3
spec:
  replicas: 1
  selector:
    matchLabels:
        component: ms3
  template:
    metadata:
      labels:
        component: ms3
    spec:
      containers:
      - name: ms3
        image: sannaman/ms3
        ports:
        - containerPort: 9093
        
---
apiVersion: v1
kind: Service
metadata:
  name: ms3
spec:
  type: NodePort
  ports:
      - port: 9093
        targetPort: 9093
        nodePort: 31593
  selector: 
      component: ms3
